### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by ArjonBu** [jetstack/version-checker#77]
Hello,

It appears that this tool doesn't support custom Gitlab repositories. It returns a 404. 

Is this the case or I am doing something wrong? 

Thank you in advance.

**Comment by infrabyte** [comment]
I like where this vc has gone. I would also like to compare versions of deployed pods in a specific namespace to the repo in Gitlab. I a token/auth would suffice but where do I configure it. As an argument maybe?

**Comment by davidcollom** [comment]
Hi @ArjonBu, appreciate that this has been some time.

Could you provide some examples of where you're seeing this? (It's been a while since I've had much exposure to Gitlab)

When you say "custom Gitlab repositories" what exactly are you referring too? Do you have any example repositories I/we could use to further debug this issue?





> I like where this vc has gone. I would also like to compare versions of deployed pods in a specific namespace to the repo in Gitlab. I suppose an token/auth would suffice but where do I configure it. As an argument maybe?

@infrabyte : Could you provide further information here? are you suggesting that version checker checks on the drift of a GitRepo? If so, this feels like its a little out of scope of version-checker, but accessing a gitlab container registry would be a valid usecase
